# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push (all branches) or pull request (only main)
  push:
    branches:
      - "**"
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      # Build minepoch
      - name: Build
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mpich
          pip3 install numpy
          pip3 install scipy
          pip3 install matplotlib
          make COMPILER=gfortran

      - name: Test
        run: |
          cp Data/two_stream.deck Data/input.deck
          ./bin/epoch3d
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 minepoch_py/test.py --disable_plots

      - name: Test-substep
        run: |
          cp Data/two_stream_substep.deck Data/input.deck
          ./bin/epoch3d
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 minepoch_py/test.py --energy_conservation=0.006 --disable_plots

      - name: Test-Parallel
        run: |
          cp Data/two_stream.deck Data/input.deck
          mpirun -np 2 ./bin/epoch3d
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 minepoch_py/test.py --disable_plots

      - name: Unit-Tests
        run: |
          cd src/unit_tests/field_evaluation
          make COMPILER=gfortran
          ./bin/field_test
          cd ../particle_position
          make COMPILER=gfortran
          ./bin/particle_load_test
          python3 check_test.py
