# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push (all branches) or pull request (only main)
  push:
    branches:
      - "**"
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs called "build" and "build-cmake"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container: docker://tomgoffrey/minepoch_deps:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build minepoch
      - name: Build
        run: |
          make COMPILER=gfortran

      - name: Test
        run: |
          cp Data/two_stream.deck Data/input.deck
          ./bin/epoch3d
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 minepoch_py/test.py --disable_plots

      - name: Test-substep
        run: |
          cp Data/two_stream_substep.deck Data/input.deck
          ./bin/epoch3d
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 minepoch_py/test.py --energy_conservation=0.006 --disable_plots

      - name: Test-Parallel
        run: |
          cp Data/two_stream.deck Data/input.deck
          mpirun -np 2 ./bin/epoch3d
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 minepoch_py/test.py --disable_plots

      - name: Test-EM-Wave
        run: |
          cp Data/em_wave.deck Data/input.deck
          mpirun -np 2 ./bin/epoch3d
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 minepoch_py/energy.py --disable_plots --energy_conservation=2e-11

      - name: Unit-Tests
        run: |
          cd src/unit_tests/field_evaluation
          make COMPILER=gfortran
          ./bin/field_test
          cd ../particle_position
          make COMPILER=gfortran
          ./bin/particle_position_test
          python3 check_test.py
          cd ../particle_momentum
          make COMPILER=gfortran
          ./bin/particle_momentum_test
          python3 check_test.py
          
  build-cmake:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container: docker://tomgoffrey/minepoch_deps:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build minepoch
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          make
          make install
          cd .. && rm -rf build

      - name: Test
        run: |
          cp Data/two_stream.deck Data/input.deck
          ./bin/epoch3d
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 minepoch_py/test.py --disable_plots

